version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: docker
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: curso
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      -  3308:3308
    expose:
      -  3308
    networks:
      -  luidi-network
  curso:
    image: repository/rest-with-springboot-2
    restart: always
    build: ./rest-with-springboot-2
    working_dir: /rest-with-springboot-2
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/curso?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 123
    ports:
      -  80:80
    command: mvn spring-boot:run
    depends_on:
      -  db
    networks:
      -  luidi-network
networks:
  luidi-network:
    driver: bridge